import { StyleSheet } from "react-native";
import { responsiveHeight,responsiveWidth } from "../../Utils/Dimension";
const style=StyleSheet.create({
    main:{
        flex:1
    },
    Headerview:{
        flex:1,
    },
    HeaderViewsub1:{
        flex:1,
        paddingLeft:responsiveWidth(4),
        paddingRight:responsiveWidth(4),
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center'
    },
    HeaderViewSub2:{
        flex:1,
        // backgroundColor:'pink',
        flexDirection:'row',
        justifyContent:'space-evenly',
        alignItems:'center'
    },
    HeaderText1:{
        fontSize:responsiveHeight(2.8),
        fontWeight:'600',
        color:'black'
    },
    HeaderCard:{
        height:responsiveHeight(8.6),
        width:responsiveWidth(43),
        backgroundColor:'rgba(143, 146, 161, 0.2)',
        borderRadius:responsiveWidth(8),
        flexDirection:'row',
        justifyContent:'space-evenly',
        alignItems:'center'
    },
    notView:{
        height:responsiveHeight(2),
        width:responsiveWidth(7),
        borderRadius:responsiveWidth(5),
        backgroundColor:'#FF3742',
        justifyContent:'center',
        alignItems:'center'
    },
    notText:{
        color:'white',
        fontSize:responsiveWidth(3),
        fontWeight:'700'
    },
    notText2:{
        color:'black',
        fontSize:responsiveWidth(3.5),
        fontWeight:'600'
    },
    seachView:{
        height:responsiveHeight(4.6),
        width:responsiveHeight(4.6),
        borderRadius:responsiveHeight(2.3),
        borderWidth:responsiveWidth(0.5),
        borderColor:'rgba(143, 146, 161, 0.2)',
        justifyContent:'center',
        alignItems:'center',
        marginLeft:responsiveWidth(2)
    },
    chatView:{
        flex:3,
        paddingLeft:responsiveWidth(3),
        paddingRight:responsiveWidth(3)
    },
    chatCard:{
        height:responsiveHeight(7),
        marginTop:responsiveHeight(2),
        flexDirection:'row',
        justifyContent:'space-between'
    },
    chatCardsub:{
        justifyContent:'center',
        marginLeft:responsiveWidth(3)
    },
    chatCardtext1:{
        fontSize:responsiveHeight(1.9),
        color:'black',
        fontWeight:'400'
    },
    chatCardtext2:{
        fontSize:responsiveHeight(1.7),
        color:'#8F92A1',
        fontWeight:'400'
    },
    timeText:{
        fontSize:responsiveHeight(1.5),
        color:'#8F92A1',
        fontWeight:'400'
    },
    mainModalView:{
        flex:1,
        backgroundColor:'#00000999',
        alignItems:'flex-end'
    },
    modalView:{
        width:responsiveWidth(40),
        height:responsiveHeight(17.1),
        backgroundColor:'white',
        borderRadius:responsiveWidth(3),
        marginTop:responsiveHeight(9),
        marginRight:responsiveWidth(4),
        padding:responsiveWidth(4)
    }
});
export default style;